# https://github.com/marketplace/actions/labeler

# Add 'documentation' label for changes to documentation
documentation: '**/*.{html,md,txt}'

# Add 'i18n' label for changes to localisation
i18n: '**/assets/*/lang/*'

# Add 'assets' label for changes to assets (except localisation)
assets:
  - '**/assets/**/*'
  - '!**/assets/*/lang/*'

# Add 'ci' label for changes to the deployment process
ci:
  - '.releaserc*'
  - '.github/workflows/publish.yml'

# Add 'build' label for changes to the build process
build:
  - '**/fabric.mod.json'
  - '**/build.gradle'
  - '**/gradle.properties'
  - '**/settings.gradle'
  - '.github/workflows/build.yml'

# Add 'modid' labels for changes to their respective codebases
#modid: 'src/**/*'
#modid-sub: 'example-submod/**/*'
