# https://semantic-release.gitbook.io

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/exec'
    - prepareCmd: sed -i -E 's/^(mod_version\s*=\s*).*$/\1${nextRelease.version}/I' gradle.properties **/gradle.properties
      publishCmd: gradle publish
  - - '@semantic-release/github'
    - assets:
        - '**/build/libs'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - '**/gradle.properties'

branches:
  - 'main'
  - 'master'
  - 'next'
  - 'next-major'
  - '+([0-9])?(.{+([0-9]),x}).x'
  - name: 'beta'
    prerelease: true
  - name: 'alpha'
    prerelease: true
