# Builds and tests the project

name: Build

# On pull requests
on:
  pull_request:
    paths:
      - '**/src/**'
      - '**/build.gradle'
      - '**/gradle.properties'
      - '**/settings.gradle'
      - .github/workflows/build.yml
      - LICENCE.txt

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v2

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: 🐘 Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: 🧪 Run tests
        run: ./gradlew check

      - name: 🔨 Build artifacts
        run: ./gradlew build publishToMavenLocal

      - name: 📦 Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: '**/build/libs/'

      - name: 📝 Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '**/build/reports/'

      - name: 🗃 Upload Maven local
        uses: actions/upload-artifact@v3
        with:
          name: maven
          path: ~/.m2/repository/
