# Builds and publishes any packages

name: Publish

# On updates to release branches
on:
  push:
    branches:
      - main
      - master
      - next
      - next-major
      - beta
      - alpha

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      packages: write

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🛂 Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 🏗 Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt

      - name: 🏗 Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: ⬇ Install Node.js dependencies
        run: npm install -g
          semantic-release@17
          @semantic-release/git
          @semantic-release/changelog
          @semantic-release/exec

      - name: 📦 Publish new release
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
